//file:noinspection All
plugins {
    id 'idea'
    id 'eclipse'
    id 'net.neoforged.moddev.legacyforge' version '+'
    id "me.modmuss50.mod-publish-plugin" version '+'
}
def platform = "Forge"
base {
    archivesName = mod_id
    group = mod_group_id
    version = "$minecraft_version-$mod_version+$platform"
}
java { toolchain.languageVersion = JavaLanguageVersion.of(17) }
legacyForge {
    version = "$minecraft_version-$forge_version"
    validateAccessTransformers = true
    parchment {
        mappingsVersion = parchment_version
        minecraftVersion = minecraft_version
    }
    runs {
        client { client(); devLogin = true }
        server { server() }
    }
    mods { "${mod_id}" { sourceSet sourceSets.main } }
}
repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.tterrag.com" } // Registrate
    maven { url = "https://maven.shedaniel.me" } // Cloth Config API
    maven { url = 'https://maven.blamejared.com' } // JEI
}
dependencies {
    modImplementation "com.simibubi.create:create-$minecraft_version:$create_version:slim"
    modImplementation "net.createmod.ponder:Ponder-Forge-$minecraft_version:$ponder_version"
    modImplementation "dev.engine-room.flywheel:flywheel-forge-$minecraft_version:$flywheel_version"
    modImplementation "com.tterrag.registrate:Registrate:$registrate_version"
    modImplementation "me.shedaniel.cloth:cloth-config-forge:$cloth_config_version"
    modImplementation "mezz.jei:jei-$minecraft_version-forge:$jei_version"
    implementation "io.github.llamalad7:mixinextras-forge:+"
    compileOnly "org.jetbrains:annotations:+"
}
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version: minecraft_version,
                             mod_id         : mod_id,
                             mod_name       : mod_name,
                             mod_display_url: mod_display_url,
                             mod_issue_url  : mod_issue_url,
                             mod_license    : mod_license,
                             mod_version    : mod_version,
                             mod_authors    : mod_authors,
                             mod_description  : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata
mixin { config "${mod_id}.mixins.json" }
jar { manifest { attributes([MixinConfigs: "${mod_id}.mixins.json"]) } }
//java { withSourcesJar() }
idea { module { downloadSources = true; downloadJavadoc = true } }
publishMods {
    file = jar.archiveFile
    changelog = file("CHANGELOG.md").text
    type = STABLE
    version = "$minecraft_version-$mod_version+$platform"
    displayName = "[$platform] $mod_name $mod_version+$minecraft_version"
    modLoaders.addAll("$platform", "NeoForge")
    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "TlQAWQCY"
        minecraftVersions.add(minecraft_version)
        requires("create", "cloth-config")
    }
    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "1233804"
        minecraftVersions.add(minecraft_version)
        requires("create", "cloth-config")
    }
}
tasks.register("fixHighlightLog") {
    fileTree(dir: "build/moddev", include: "**/*Log4j2.xml").each { file -> file.text = file.text.replaceAll("Forge", "") }
}
