# Gradle
org.gradle.jvmargs=-Xmx2G -XX\:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
java_version=21
# Mod
mod_id=create_cyber_goggles
mod_name=Create: Cyber Goggles
mod_license=MIT
mod_version=3.2.0
mod_group_id=io.github.forgestove
mod_authors=ForgeStove
mod_display_url=https://modrinth.com/mod/create-cyber-goggles
mod_issue_url=https://github.com/ForgeStove/CreateCyberGoggles/issues
mod_description=A client-side mod for Create that provides modular assistance features.
# Version
minecraft_version=1.21.8
fabric_loader_version=0.17.2
fabric_api_version=0.133.4+1.21.8
parchment_version=2025.09.14
yarn_mappings=1.21.8+build.1
create_version=73a6547dae
cloth_config_version=19.0.147
modmenu_version=15.0.0
rei_version=20.0.811
# Loader
loader=fabric
upper_loader=Fabric
other_loader=Quilt
