# Gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
javaVersion=21
# Mod
modId=create_cyber_goggles
modName=CreateCyberGoggles
modDisplayName=Create: Cyber Goggles
modLicense=MIT
modVersion=6.7.4
modGroupId=io.github.forgestove
modAuthors=ForgeStove
modDisplayUrl=https://modrinth.com/mod/create-cyber-goggles
modIssueUrl=https://github.com/ForgeStove/CreateCyberGoggles/issues
modDescription=A client-side mod for Create that provides modular assistance features.
# Version
mcVersion=1.21.1
loaderVersion=21.1.213
parchmentVersion=2024.11.17
createMinVersion=6.0.7
createVersion=6.0.9-182
ponderVersion=1.0.69
flywheelVersion=1.0.6-beta-38
registrateVersion=MC1.21-1.3.0+67
clothConfigVersion=15.0.140
jeiVersion=19.21.1.300
jadeVersion=15.10.3
ceiVersion=2.2.3
dragonPlusVersion=1.8.1
# Loader
loader=neoforge
loaderCap=NeoForge
