# Gradle
org.gradle.jvmargs=-Xmx2G -XX\:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
java_version=21
# Mod
mod_id=create_cyber_goggles
mod_name=Create: Cyber Goggles
mod_license=MIT
mod_version=6.1.3
mod_group_id=io.github.forgestove
mod_authors=ForgeStove
mod_display_url=https://modrinth.com/mod/create-cyber-goggles
mod_issue_url=https://github.com/ForgeStove/CreateCyberGoggles/issues
mod_description=A client-side mod for Create that provides modular assistance features.
# Version
minecraft_version=1.21.1
loader_version=21.1.209
parchment_version=2024.11.17
create_version=6.0.7-117
ponder_version=1.0.61
flywheel_version=1.0.4
registrate_version=MC1.21-1.3.0+62
cloth_config_version=15.0.140
jei_version=19.21.1.300
jade_version=15.10.0+neoforge
# Loader
loader=neoforge
upper_loader=NeoForge
