modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "${modIssueUrl}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
displayURL = "${modDisplayUrl}"
description = '''${modDescription}'''
logoFile = "icon.png"
logoBlur = false

[[dependencies."${modId}"]]
modId = "forge"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${modId}"]]
modId = "minecraft"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${modId}"]]
modId = "create"
mandatory = true
versionRange = "[0.5,1.0)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${modId}"]]
modId = "cloth_config"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${modId}"]]
modId = "jei"
mandatory = false
versionRange = "0"
ordering = "NONE"
side = "CLIENT"
