modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "${mod_issue_tracker_url}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL= "${mod_display_url}"
description = '''${mod_description}'''
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId="create"
type="required"
ordering="NONE"
side="CLIENT"
