package com.ForgeStove.create_cyber_goggles;
import net.neoforged.neoforge.common.ModConfigSpec;
import net.neoforged.neoforge.common.ModConfigSpec.*;
public class Config {
	public static final Builder CLIENT = new Builder();
	public static final ModConfigSpec CLIENT_SPEC;
	public static final ConfigValue<Boolean> alwaysAllowRiding;
	public static final ConfigValue<Boolean> preventFalling;
	public static final ConfigValue<Integer> separationDistance;
	public static final ConfigValue<Integer> separationHeight;
	public static final ConfigValue<Boolean> enhancedConnection;
	public static final ConfigValue<Boolean> forcedBackend;
	public static final ConfigValue<Boolean> enableInSurvival;
	public static final ConfigValue<Boolean> enableInCreative;
	public static final ConfigValue<Boolean> enableInSpectator;
	public static final ConfigValue<Boolean> enableInAdventure;
	public static final ConfigValue<Boolean> enhancedInfo;
	public static final ConfigValue<Boolean> enhancedStoreRender;
	public static final ConfigValue<Boolean> enableDepotRender;
	public static final ConfigValue<Boolean> enableOpenFilterScreen;
	public static final ConfigValue<Boolean> enableKineticEffect;
	public static final ConfigValue<Boolean> preciseNumbers;
	public static final ConfigValue<Boolean> alwaysAllowRotating;
	static {
		CLIENT.push("ChainConveyor");
		alwaysAllowRiding = CLIENT.comment("Riding without wrench").define("alwaysAllowRiding", false);
		preventFalling = CLIENT.comment("Prevent falling off chain conveyors").define("preventFalling", false);
		separationDistance = CLIENT.comment("Minimum relative falling distance").define("separationDistance", 3);
		separationHeight = CLIENT.comment("Minimum relative falling height").define("separationHeight", -1);
		enhancedConnection = CLIENT.comment("Enhanced chain conveyor connection").define("enhancedConnection", true);
		CLIENT.pop();
		CLIENT.push("Flywheel");
		forcedBackend = CLIENT.comment("Force Allow flywheel backend").define("forcedBackend", false);
		CLIENT.pop();
		CLIENT.push("Goggles");
		enableInSurvival = CLIENT.comment("Enable goggles in Survival mode").define("enableInSurvival", true);
		enableInCreative = CLIENT.comment("Enable goggles in creative mode").define("enableInCreative", true);
		enableInSpectator = CLIENT.comment("Enable goggles in spectator mode").define("enableInSpectator", true);
		enableInAdventure = CLIENT.comment("Enable goggles in adventure mode").define("enableInAdventure", true);
		enhancedInfo = CLIENT.comment("Show more information in the goggles overlay").define("enhancedInfo", true);
		enhancedStoreRender = CLIENT.comment("Enhanced store rendering").define("enhancedStoreRender", true);
		enableDepotRender = CLIENT.comment("Render item stack tooltip on depot").define("enableDepotRender", true);
		enableOpenFilterScreen = CLIENT.comment("Open filter by hotkey").define("enableOpenFilterScreen", true);
		enableKineticEffect = CLIENT.comment("Show target kinetic block effect").define("enableKineticEffect", true);
		preciseNumbers = CLIENT.comment("Show precise numbers in the goggles overlay").define("preciseNumbers", true);
		CLIENT.pop();
		CLIENT.push("Wrench");
		alwaysAllowRotating = CLIENT.comment("Always allow rotating block").define("alwaysAllowRotating", true);
		CLIENT.pop();
		CLIENT_SPEC = CLIENT.build();
	}
}
