name: Publish Mods

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: publish-mods
  cancel-in-progress: false

jobs:
  publish:
    name: Run publishMods
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Java Version
        id: java_version
        run: echo "version=$(grep '^javaVersion=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.java_version.outputs.version }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Mod
        run: ./gradlew build

      - name: Publish via Gradle
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew --no-daemon publishMods
